# ~/.JuliaFormatter.toml

# Optional opinionated base:
style = "sciml"          # or "default", "blue", "sciml", "yas", "minimal"

# Line width: pick your poison (88 like Black is popular)
# margin = 88             # default is 92; lines longer than this are split

# A few sensible toggles (all optional)
indent = 4
remove_extra_newlines = true
always_for_in = true
whitespace_typedefs = true
# Keep spaces around operators inside indices (if you prefer)
# whitespace_ops_in_indices = true
